version: '3'
services:
  ts-api-docker:
    restart: always
    build: .
    environment:
      PING_LISTEN_PORT: 3000
    deploy:
      replicas: 4
    volumes:
      - ./:/usr/src/app

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ts-api-docker