apiVersion: apps/v1
kind: ReplicaSet
metadata:
  namespace: default
  name: pod2
spec:
  replicas: 4
  selector:
    matchLabels:
      app: pod2
  template:
    metadata:
      labels:
        app: pod2
    spec:
      containers:
      - name: api
        image: registry.cluster.wik.cloud/public/echo
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: mon-service
spec:
  selector:
    app: pod2
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP