apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod3
spec:
  replicas: 4
  selector:
    matchLabels:
      app: pod3
  template:
    metadata:
      labels:
        app: pod3
    spec:
      containers:
      - name: api
        image: registry.cluster.wik.cloud/public/echo
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%