version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: reverse_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - wordpress

  wordpress:
    image: wordpress:latest
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: toto
      WORDPRESS_DB_PASSWORD: toto
      WORDPRESS_DB_NAME: database
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_REDIS_HOST', 'redis');
        define('WP_CACHE_KEY_SALT', 'example_salt');
    volumes:
      - wordpress_data:/var/www/html

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: toto
      MYSQL_PASSWORD: toto
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis_data:/data

volumes:
  wordpress_data:
  mysql_data:
  redis_data:
